### ISSUE TITLE
Implement CLI functionality

### ISSUE THREAD

**Issue by MrRedAmber** [blacktop/virustotal-api#13]
```bash
$ virustotal --hash $MD5 --apikey $VT_APK
```
of course with more features than just hash lookups!

**Comment by MrRedAmber** [comment]
see MrRedAmber/virustotal-api

**Comment by blacktop** [comment]
This is just meant to be a virustotal API python SDK to be used by people like you to create other awesome things. 🐳

**Comment by MrRedAmber** [comment]
I C
