### ISSUE TITLE
somethings wrong with the repository's front page

### ISSUE THREAD

**Issue by MrRedAmber** [blacktop/virustotal-api#14]

**Comment by blacktop** [comment]
see https://github.com/github/markup/issues/1015 and https://github.com/github/markup/issues/1016

**Comment by blacktop** [comment]
I just added two spaces at the end of a line and it fixed it... oh github 😏

**Comment by MrRedAmber** [comment]
I was scared 😨 think about the 🐳 🐳 🐳 's!!!!!!!!!!!!!!!!!!
