### ISSUE TITLE
get_url_report with a list of scan_ids

### ISSUE THREAD

**Issue by SysuJayce** [blacktop/virustotal-api#27]
Hi,
  I found that it is supported to retrieve the scan report with a list of scan ids. However, I cant find out how to retrieve the scan report in one single call.

  I have tried this
```
>>> url[:5]
['19832fd18326dbddf226b162495b279ee7acc8ca6f42161abd0edfd0a9ea70c8-1540712460\n', '958765cc15195af3a9ce7bfa1d5993e215bfca3d6aa44f1f3198afbd6b8fd9dd-1540712460\n', '34b0efce5b90b89f9fc6e2d2d4b0da127fcace8247575ecae0ba43764ce56669-1540712460\n', 'fa89ca7b2ba7b833583ded17cb43c536d1a7dd44d6d43a90d8e20319cdc630eb-1540712460\n', '9d9dbb0d9713cd6219f45596f4158d3fb4d456045da1d0d921b6cc5c68f94de1-1540712461\n']
>>> response = vt.get_url_report(url)
>>> response
{'error': "('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))"}
```

  Is there any problem with my code? Plz help pointing out, thanks a lot.

**Comment by KadenLNelson** [comment]
I don't have any testing environment locally but you may need to pass a string instead of an array try 
`vt.get_url_report(url.join())`

**Comment by joseph-hannon** [comment]
API docs say "_When sending multiples, the scan_ids or URLs must be separated by a new line character._" So @KadenLNelson's solution should work.

https://github.com/blacktop/virustotal-api/blob/master/virus_total_apis/api.py#L170

**Comment by CDuPlooy** [comment]
The package comments now read 

>         You can also specify a CSV list made up of a combination of hashes and scan_ids
>        (up to 4 items with the standard request rate), this allows you to perform a batch
>        request with one single call.

So the below would be more appropriate

````python
      response = vt.get_file_report(", ".join(urls) + "\n")
````

I can submit a PR to check if the argument is an array or tuple instead of a single string and format it correctly before passing it to the rest of the function if this project is still active.

**Comment by blacktop** [comment]
This should be closed now thanks to @CDuPlooy and @KadenLNelson 🎉
